// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr0HJHH2DeLfZuXKIcWrXNEskpELwHqaA',
    appId: '1:152742107512:web:199f02e597019000a1d08d',
    messagingSenderId: '152742107512',
    projectId: 'uro-app-f3690',
    authDomain: 'uro-app-f3690.firebaseapp.com',
    storageBucket: 'uro-app-f3690.appspot.com',
    measurementId: 'G-5ESDLPYQHV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0Zx36N6Vz7L0c_lqu-uIc2stzFJCrQRs',
    appId: '1:152742107512:android:d4c44ba1a0b94b59a1d08d',
    messagingSenderId: '152742107512',
    projectId: 'uro-app-f3690',
    storageBucket: 'uro-app-f3690.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpeCCip62xV1s_die0xxdxQsRwExfBedI',
    appId: '1:152742107512:ios:6f1cdd06d455e291a1d08d',
    messagingSenderId: '152742107512',
    projectId: 'uro-app-f3690',
    storageBucket: 'uro-app-f3690.appspot.com',
    iosClientId: '152742107512-0eviievcmkilgaos1j1d1v37dhobret2.apps.googleusercontent.com',
    iosBundleId: 'com.example.uroapplication',
  );
}
